before_commands:
    - composer install --dev
tools:
    php_code_coverage:
        test_commend: "phpunit"
        filter:
            paths: ["src/*"]
    php_cpd:
        enabled: true
        filter:
            paths: ["src/*"]
    php_sim:
        enabled: true
        filter:
            paths: ["src/*"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]
    php_pdepend:
        enabled: true
        filter:
            paths: ["src/*"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["src/*"]