language: php

sudo: false

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: nightly
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

script:
  - travis_retry composer update --no-interaction --prefer-source