# Documentation website
title: "URI"
tagline: "Modern API to process URI in PHP."
description: "Modern API to process URI in PHP"
google_analytics_tracking_id: UA-46050814-14
# Github repository
repository: 'uri'
author:
    name: 'Ignace Nyamagana Butera'
    twitter_account: 'nyamsprod'
support: 'Once a new major version is released, the previous stable release remains supported for six more months through patches and security fixes.'
