# Documentation website
title: "URI"
tagline: "Modern API to process URI in PHP."
description: "Modern API to process URI in PHP"
google_analytics_tracking_id: UA-46050814-14
# Github repository
repository: 'uri'
author:
    name: 'Ignace Nyamagana Butera'
    twitter_account: 'nyamsprod'
# Homepage specific
highlights:
  description: 'This suite of packages provides simple and intuitive classes to parse, validate, format and manipulate URIs and their components. It is built to enable working with
        any kind of RFC3986 compliant URI through extensions and middlewares.'
  features:
      - 'Simple and extensible API'
      - '<a href="http://tools.ietf.org/html/rfc3986">RFC3986</a> compliant'
      - 'Implements <a href="http://www.php-fig.org/psr/psr-7/">PSR-7</a> <code>UriInterface</code> interface'
      - 'Framework-agnostic'
support: 'Once a new major version is released, the previous stable release remains supported for six more months through patches and security fixes.'
